const express = require('express');
const router = express.Router();
const authMiddleware = require('../../middleware/authMiddleware');
const { list, markRead, markAllRead, dismiss } = require('../../controllers/notification.controller');

/**
 * @swagger
 * tags:
 *   name: Notifications
 *   description: In-app notifications generated by feedback and contact submissions
 */

/**
 * @swagger
 * /notifications:
 *   get:
 *     tags: [Notifications]
 *     summary: List all notifications (newest first)
 *     description: Returns up to 100 notifications. Requires authentication.
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *           default: 50
 *         description: Max number of notifications to return (capped at 100)
 *     responses:
 *       200:
 *         description: Array of notification objects
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Notification'
 *       401:
 *         description: Authentication required
 *       500:
 *         description: Server error
 */
router.get('/', authMiddleware, list);

/**
 * @swagger
 * /notifications/read-all:
 *   patch:
 *     tags: [Notifications]
 *     summary: Mark all notifications as read
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: All notifications marked as read
 *       401:
 *         description: Authentication required
 */
router.patch('/read-all', authMiddleware, markAllRead);

/**
 * @swagger
 * /notifications/{id}/read:
 *   patch:
 *     tags: [Notifications]
 *     summary: Mark a single notification as read
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Notification document ID
 *     responses:
 *       200:
 *         description: Updated notification
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Notification'
 *       404:
 *         description: Notification not found
 *       401:
 *         description: Authentication required
 */
router.patch('/:id/read', authMiddleware, markRead);

/**
 * @swagger
 * /notifications/{id}:
 *   delete:
 *     tags: [Notifications]
 *     summary: Dismiss (delete) a notification
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Notification document ID
 *     responses:
 *       200:
 *         description: Notification dismissed
 *       401:
 *         description: Authentication required
 */
router.delete('/:id', authMiddleware, dismiss);

module.exports = router;

/**
 * @swagger
 * components:
 *   schemas:
 *     Notification:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *           example: 664f1a2b3c4d5e6f7a8b9c0d
 *         type:
 *           type: string
 *           enum: [feedback, contact]
 *           example: feedback
 *         title:
 *           type: string
 *           example: "New feedback received"
 *         description:
 *           type: string
 *           example: "Achal Kumar left a ★★★★☆ feedback in category: general"
 *         meta:
 *           type: object
 *           example: { rating: 4, category: "general" }
 *         read:
 *           type: boolean
 *           example: false
 *         createdAt:
 *           type: string
 *           format: date-time
 *         updatedAt:
 *           type: string
 *           format: date-time
 */
